### ISSUE TITLE
compile intermediate screen definition file

### ISSUE THREAD

**Issue by jvedev** [Pantheon-Research/pfmController#27]
when parsing an idl file an intermediate file could be created (compiled) 

this file will have the rendered ouput per field so only authorisation has to be done on runtime

```yaml

#parser_version indicates what parser generated this file when the current parser version is higher this
#file will be re generated on the fly
parser_version: 1.0.0

# when at compile time  fields to be authorised are known 
# this might be indicated in here 
# read is optional
# readwrite for labels  
    

- line : <div id="BLURDIV"></div>
- line : <label id="AVTCD_LBL" for="AVTCD_ENT" class="  xpos002 line1    xLeft " data-font-size="*MEDIUM">Tekstcode</label>
- line : <input autocomplete="off" data-datatype="*DTA" tabindex="1020" maxlength="5" data-protected="true" id="AVTCD_ENT" name="AVTCD_ENT" value="SRL" class="  xpos020 line1   data  xInpLeft05 " type="text" data-line="1" data-xpos="20" data-precision="5" readonly="" data-old-value="SRL" data-focus-action="INP.handleOnFocus" data-blur-action="INP.handleOnBlur">
- line : <output id="AVTCD_IDX" class="  xpos030 line1   data  xLeft    " data-value-from-id="AVTCD_IDX" data-datatype="*DTA" data-hidden="true" data-font-size="*MEDIUM"></output>
- line :
  aut: some criteria or idicator or hatever we need
  field: AVTID_ENT
  readwrite: <label id="AVTID_LBL" for="AVTID_ENT" class="  xpos002 line2    xLeft " data-font-size="*MEDIUM">Tekst identificatie</label>
- line :
    aut: AVTID_AUTH= 10 # optional when know and if this would be a good approach some criteria or idicator or hatever we need 
    field: AVTID_ENT
    read:  <output data-datatype="*DTA" tabindex="2020" id="AVTID_ENT" name="AVTID_ENT" value="" class="  xpos020 line2   data  xInpLeft25 " type="text" data-line="2" data-xpos="20" data-precision="25" >
    write: <input autocomplete="off" data-datatype="*DTA" tabindex="2020" maxlength="25" data-autosubmit="true" id="AVTID_ENT" name="AVTID_ENT" value="" class="  xpos020 line2   data  xInpLeft25 " type="text" data-line="2" data-xpos="20" data-precision="25" data-old-value="" data-focus-action="INP.handleOnFocus" data-blur-action="INP.handleOnBlur" data-select-all-now="false">
- line :   <output id="AVTID_IDX" class="  xpos030 line2   data  xLeft    " data-value-from-id="AVTID_IDX" data-datatype="*DTA" data-hidden="true" data-font-size="*MEDIUM"></output>
- line :   <label id="AVTXT_LBL" for="AVTXT" class="  xpos002 line4    xLeft " data-font-size="*MEDIUM">Aanvullende tekst</label>
- line :   <pre id="AVTXT" class="  xpos020 line4   memo  xLeft105 lines20" data-value-from-id="AVTXT" data-datatype="*MEMO" data-font-size="*MEDIUM" value="" data-old-value="" data-select-all-now="false"></pre>

# if we can't determine what input should be served as an output or omitted at compile time
# every line should have a field to base authentication on
# in this case
# when  AVTID_ENT is authenticated for read it wil output readwrite and read members
# when  AVTID_ENT is authenticated for write it wil output readwrite and write members
# when  AVTID_ENT is not authenticated for either read or write it not output anything
 
- line :
    field: AVTID_ENT
    readwrite: <label id="AVTID_LBL" for="AVTID_ENT" class="  xpos002 line2    xLeft " data-font-size="*MEDIUM">Tekst identificatie</label>
- line :
    field: AVTID_ENT
    read:  <output data-datatype="*DTA" tabindex="2020" id="AVTID_ENT" name="AVTID_ENT" value="" class="  xpos020 line2   data  xInpLeft25 " type="text" data-line="2" data-xpos="20" data-precision="25" >
    write: <input autocomplete="off" data-datatype="*DTA" tabindex="2020" maxlength="25" data-autosubmit="true" id="AVTID_ENT" name="AVTID_ENT" value="" class="  xpos020 line2   data  xInpLeft25 " type="text" data-line="2" data-xpos="20" data-precision="25" data-old-value="" data-focus-action="INP.handleOnFocus" data-blur-action="INP.handleOnBlur" data-select-all-now="false">

```
